branch: master
check:
- CKV_AWS_28
- CKV2_AWS_16
- CKV_AWS_66
- CKV_AWS_228
- CKV_AWS_250
- CKV_AWS_16
- CKV_AWS_21
- CKV_AWS_18
- CKV_AWS_96
directory:
- .
download-external-modules: DOWNLOAD_EXTERNAL_MODULES
evaluate-variables: true
external-checks-dir:
- ./customChecks/terraform/checkov/custom-policies/aws
external-modules-download-path: .external_modules
framework:
- terraform
- terraform_plan
run-all-external-checks: true
